version: "{build}"

environment:
    global:
         PYTHON_VERSION: "3.x.x"

install:
  - cinst haxe -y
  - cinst curl -y
  - cmd: mklink C:\Python34-x64\python3.exe C:\Python34-x64\python.exe
  - set PATH=%PATH%;C:\Python34-x64
  - RefreshEnv
  - haxelib setup %HOME%/haxelib
  - haxelib install hxcpp
  - haxelib install hxjava
  - haxelib install hxcs
  - haxelib list

build_script:
  - REM [Building NEKO]
  - haxe tests.hxml -neko bin/test.n
  - REM [Building JAVASCRIPT]
  - haxe tests.hxml -js bin/test.js
  - REM [Building PHP]
  - haxe tests.hxml -php bin/php
  - REM [Building PHP7]
  - haxe tests.hxml -D php7 -php bin/php7
  - REM [Building PYTHON]
  - haxe tests.hxml -python bin/test.py
  - REM [Building JAVA]
  - haxe tests.hxml -java bin/java
  - REM [Building C#]
  - haxe tests.hxml -cs bin/cs
  - REM [Building C++]
  - haxe tests.hxml -cpp bin/cpp

test_script:
  - REM [Running NEKO]
  - neko bin/test.n
  - REM [Running JAVASCRIPT]
  - node bin/test.js
  - REM [Running PHP 5.6]
  - cinst php --version=5.6.32 -y
  - C:\tools\php56\php.exe bin/php/index.php
  - REM [Running PHP 7.0]
  - cuninst php
  - cinst php --version=7.0.26 -y
  - C:\tools\php70\php.exe bin/php7/index.php
  - cuninst php
  - REM [Running PHP 7.1]
  - cinst php --version=7.1.12 -y
  - C:\tools\php71\php.exe bin/php7/index.php
  - cuninst php
  - REM [Running PHP 7.2]
  - cinst php --version=7.2.0 -y
  - C:\tools\php72\php.exe bin/php7/index.php
  - REM [Running PYTHON]
  - python --version
  - python bin/test.py
  - REM [Running JAVA]
  - java -jar bin/java/TestAll.jar
  - REM [Running C#]
  - bin/cs/bin/TestAll.exe
  - REM [Running C++]
  - bin/cpp/TestAll.exe